### ISSUE TITLE
command line argument can be passed to ...

### ISSUE THREAD

**Issue by ghost** [cliveontoast/GoMoPho#14]
how or where do I insert this command line?
.\GoMoPhoConsole.exe d "c:\temp\New Folder" s "c:\temp\Processed"
sry, if it´s obvious but i´m new to this stuff
and would it be possible to just type 'g' for gifs like pressing 'a' for more information?

**Comment by cliveontoast** [comment]
Hi StolenBlock,

Thanks for trying out the application. I could spend some time making a GUI for windows users. It's a TODO for me.

It should be possible to do your suggestion. It's a good suggestion. I'll see when I have the time in the near future.

In the mean time, [Open up a command line in the GoMoPho folder](https://www.google.com/search?q=open+up+command+line+at+current+folder) (OMG I just found out you can type cmd in the address bar, awesome!)

Once you have the command-line application open (it's a black or blue box application). you should then be able to type in that command you wish i.e.

`GoMoPhoConsole.exe d "c:\temp\New Folder" s "c:\temp\Processed" g`

then press ENTER to extract the gifs.

The window would have something like the following text just before you press ENTER

```
Microsoft Windows [Version 10.0.16299.1868]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\Clive\Downloads\GoMoPho.Windows.2.1.0>GoMoPhoConsole.exe  d "c:\temp\New Folder" s "c:\temp\Processed" g`
```

**Comment by SvenTafvelin** [comment]
Hi Clive,
I have among a number of cameras a Pixel 3XL which I always try to keep updated with the latest software.
I have by "accident" taken a number of pictures with the Pixel with the format motion picture. I'm not
interested in the video and searched for an application to remove the video part. I found that your application
could be used and I have tested it on a Windows 10 workstation.

For most pictures the application worked as described. But in September this year the Google photo app changed
convention on how the resultings files are named. For example look at  https://9to5google.com/2020/08/20/google-camera-7-5-pxl/      

When I found out my "accident" half a year ago I have switched off the motion picture feature in my Pixel phota app.
Since September I'm getting picture files named   like   PXL_20200921_143906890.jpg
When these files are processed by your application it gets into trouble and responds:

"Searching ../bilderPixel3-20201103\PXL_20200921_143906890.jpg   Did not find known video, trying generic approachFailed to find the video out of 0 possibilites
Please report this output to https://github.com/cliveontoast/GoMoPho/issues and attach your moving image jpeg file"

I investigated the situation further on and switched on the motion picture feature and took a few pictures. They got
names like      PXL_20201103_195534480.MP.jpg      Note the ending!

These are processed correctly by the application.

Therefore my outsider's guess is that you application wrongly beleives that files like PXL_20200921_143906890.jpg
contains video but they don't. I have asked the photo app not to include video!

I will attach an example file for you experiments.

Regards 
Sven Tafvelin
![PXL_20200921_143906890](https://user-images.githubusercontent.com/38525448/98270532-40084400-1f8f-11eb-896a-72b28ce8fdbf.jpg)

**Comment by cliveontoast** [comment]
Hi @SvenTafvelin,

Appreciate the example picture. I'll get onto this shortly. Sorry for the very late reply.

Have a read of https://github.com/cliveontoast/GoMoPho/issues/19

You should be able to update the `.config` file in the folder line 4 to find these new PXL*.MP.jpg files

**Comment by cliveontoast** [comment]
@SvenTafvelin  I forgot a long while back, I added an option in the arguments of the program you can specify the pattern to search for when running the application.

`dotnet .\GoMoPhoCoreConsole.dll p "PXL*MP.jpg"`

**Comment by cliveontoast** [comment]
Hi @SvenTafvelin  

Thanks for reporting the issue. I've made some updates, go [grab the lastest version](https://github.com/cliveontoast/GoMoPho/releases) and have another go
