### ISSUE TITLE
Not supporting motion photos anymore on Android 12

### ISSUE THREAD

**Issue by gXxshock** [cliveontoast/GoMoPho#23]
I've tried the latest Windows build v3.3 and it does not extract videos anymore. I've tested it with motion photos from Android 12 on Pixel 4a. Older Android 11 photos still work. Seems like Google has changed the file structure.

**Comment by hmueller01** [comment]
I have the same issue here.
```
GoMoPho.CrossPlatform.3.3> dotnet GoMoPhoCoreConsole.dll d .
Welcome to google motion photos extractor.
If you provide a folder that contains google motion photos,
then I will extract any videos found
Found the following number of google motion photos: 1
Searching ./PXL_20211227_151322429.MP.jpg   Did not find known video, trying generic approachFailed to find the video out of 1 possibilites
Please report this output to https://github.com/cliveontoast/GoMoPho/issues and attach your moving image jpeg file
Finished. Processed 1 files, found 0 videos for 1 images files.
Press any key to exit
```
Attached an example file for further investigations.
[PXL_20211227_151322429.MP.zip](https://github.com/cliveontoast/GoMoPho/files/7780808/PXL_20211227_151322429.MP.zip)

**Comment by PaulRotter** [comment]
Add the following line to the config (near the existing line with "Mp4Header_mp42_isommp42")
`<add key="Mp4Header_mp42_isommp41" value="00 00 00 1C 66 74 79 70 69 73 6F 6D" />` 

Found the crucial hint to ftypisom at https://mjanja.ch/2021/10/stripping-embedded-mp4s-out-of-android-12-motion-photos/ took the signature 66 74 ... from https://en.wikipedia.org/wiki/List_of_file_signatures and looked at the file in hex for 1C instead of 18. The length of the extracted video matches the EXIF tag "Directory Item Length" in bytes and the video looks fine.

**Comment by RoxMarty** [comment]
Could you please add support for Android 15?
Because I'm seeing this:

> Welcome to google motion photos extractor.
> If you provide a folder that contains google motion photos,
> then I will extract any videos found
...
> Found the following number of google motion photos: 0
> Finished. Processed 0 files, found 0 videos for 0 images files.
> Press any key to exit
> 

An example of a motion photo that is not found:
![Image](https://github.com/user-attachments/assets/bcacc3bd-6458-47d7-95d3-f6d018e81a09)
